### PR TITLE
Replace sharing methods

### PR DESCRIPTION
**Pull request by ScharfViktor**
Sorry that the PR is huge, but I couldn't make it smaller since there are so many dependencies

replacing share endpoint. Using new SharingNew api instead of the deprecated ocs
- create_space_invitation
- create_share_invitation
- delete_share_invitation

- Since SharingNg uses recipientUuid (ocs used userName) I added intermediate step `findUser` or `findGroup` to `koko-platform-090-create-remove-group-share-ramping-k6.js` test

#### tests earlier:

Screenshot 2024-08-08 at 10 15 56

#### tests now: 

Screenshot 2024-08-08 at 10 19 23

### CODE REVIEW

**Comment by fschade** [comment]
thanks, 2 things:

- can u rebase ur pr, the gitignore is updated, artifacts are no longer part of the repo
- can you please remove all other platforms, with that change the endpoints are incompatible
thanks :)

**Comment by ScharfViktor** [comment]
> thanks, 2 things:
> 
> * can u rebase ur pr, the gitignore is updated, artifacts are no longer part of the repo

first need update `next` branch
https://github.com/owncloud/cdperf/pull/65

> * can you please remove all other platforms, with that change the endpoints are incompatible

will be implemented in the next PRs

**Comment by ScharfViktor** [comment]
@fschade is it okey if I merge this PR?

I have a `Merge pull request` button, but I want to follow our workflow (review->approve->merge) anyway.

**Comment by butonic** [comment]
I cannot compile this:
```
# pnpm install
Scope: all 6 workspace projects
 WARN  1 deprecated subdependencies found: string-similarity@4.0.4
Already up to date
Progress: resolved 779, reused 731, downloaded 0, added 0, done
Done in 2.4s
# pnpm build

> @2.0.0-rc.5 build /root/cdperf
> turbo run build --no-daemon

• Packages in scope: @ownclouders/eslint-config, @ownclouders/k6-tdk, @ownclouders/k6-tests, @ownclouders/tsconfig, @ownclouders/turbowatch
• Running build in 5 packages
• Remote caching disabled
@ownclouders/turbowatch:build: cache hit, suppressing logs 44c192a886661f45
@ownclouders/k6-tdk:build: cache miss, executing fd466463e1ce18a5
@ownclouders/k6-tdk:build: 
@ownclouders/k6-tdk:build: > @ownclouders/k6-tdk@0.0.1 build /root/cdperf/packages/k6-tdk
@ownclouders/k6-tdk:build: > concurrently pnpm:build:*
@ownclouders/k6-tdk:build: 
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [artifacts] > @ownclouders/k6-tdk@0.0.1 build:artifacts /root/cdperf/packages/k6-tdk
@ownclouders/k6-tdk:build: [artifacts] > node build.mjs
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [types] 
@ownclouders/k6-tdk:build: [types] > @ownclouders/k6-tdk@0.0.1 build:types /root/cdperf/packages/k6-tdk
@ownclouders/k6-tdk:build: [types] > tsc --outDir dist/types
@ownclouders/k6-tdk:build: [types] 
@ownclouders/k6-tdk:build: [artifacts] CLI Building entry: src/index.ts, src/auth/index.ts, src/client/index.ts, src/endpoints/index.ts, src/values/index.ts, src/utils/index.ts
@ownclouders/k6-tdk:build: [artifacts] CLI Using tsconfig: tsconfig.json
@ownclouders/k6-tdk:build: [artifacts] CLI tsup v7.0.0
@ownclouders/k6-tdk:build: [artifacts] CLI Building entry: src/index.ts, src/auth/index.ts, src/client/index.ts, src/endpoints/index.ts, src/values/index.ts, src/utils/index.ts
@ownclouders/k6-tdk:build: [artifacts] CLI Using tsconfig: tsconfig.json
@ownclouders/k6-tdk:build: [artifacts] CLI tsup v7.0.0
@ownclouders/k6-tdk:build: [artifacts] CLI Target: esnext
@ownclouders/k6-tdk:build: [artifacts] CJS Build start
@ownclouders/k6-tdk:build: [artifacts] CJS You have emitDecoratorMetadata enabled but @swc/core was not installed, skipping swc plugin
@ownclouders/k6-tdk:build: [artifacts] CLI Target: esnext
@ownclouders/k6-tdk:build: [artifacts] ESM Build start
@ownclouders/k6-tdk:build: [artifacts] ESM You have emitDecoratorMetadata enabled but @swc/core was not installed, skipping swc plugin
@ownclouders/k6-tdk:build: [artifacts] ✘ [ERROR] Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [artifacts]     src/endpoints/index.ts:17:51:
@ownclouders/k6-tdk:build: [artifacts]       17 │ ..._fileSharing_v1_shares from './ocs-v2-apps-file_sharing-v1-shares'
@ownclouders/k6-tdk:build: [artifacts]          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [artifacts] ✘ [ERROR] Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [artifacts]     src/endpoints/index.ts:17:51:
@ownclouders/k6-tdk:build: [artifacts]       17 │ ..._fileSharing_v1_shares from './ocs-v2-apps-file_sharing-v1-shares'
@ownclouders/k6-tdk:build: [artifacts]          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [artifacts] CJS Build failed
@ownclouders/k6-tdk:build: [artifacts] /root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1636
@ownclouders/k6-tdk:build: [artifacts]   let error = new Error(`${text}${summary}`);
@ownclouders/k6-tdk:build: [artifacts]               ^
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [artifacts] Error: Build failed with 1 error:
@ownclouders/k6-tdk:build: [artifacts] src/endpoints/index.ts:17:51: ERROR: Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"
@ownclouders/k6-tdk:build: [artifacts]     at failureErrorWithLog (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1636:15)
@ownclouders/k6-tdk:build: [artifacts]     at /root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1048:25
@ownclouders/k6-tdk:build: [artifacts]     at runOnEndCallbacks (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1471:45)
@ownclouders/k6-tdk:build: [artifacts]     at buildResponseToResult (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1046:7)
@ownclouders/k6-tdk:build: [artifacts]     at /root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1075:16
@ownclouders/k6-tdk:build: [artifacts]     at responseCallbacks.<computed> (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:697:9)
@ownclouders/k6-tdk:build: [artifacts]     at handleIncomingPacket (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:752:9)
@ownclouders/k6-tdk:build: [artifacts]     at Socket.readFromStdout (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:673:7)
@ownclouders/k6-tdk:build: [artifacts]     at Socket.emit (node:events:517:28)
@ownclouders/k6-tdk:build: [artifacts]     at addChunk (node:internal/streams/readable:368:12) {
@ownclouders/k6-tdk:build: [artifacts]   errors: [
@ownclouders/k6-tdk:build: [artifacts]     {
@ownclouders/k6-tdk:build: [artifacts]       detail: undefined,
@ownclouders/k6-tdk:build: [artifacts]       id: '',
@ownclouders/k6-tdk:build: [artifacts]       location: {
@ownclouders/k6-tdk:build: [artifacts]         column: 51,
@ownclouders/k6-tdk:build: [artifacts]         file: 'src/endpoints/index.ts',
@ownclouders/k6-tdk:build: [artifacts]         length: 38,
@ownclouders/k6-tdk:build: [artifacts]         line: 17,
@ownclouders/k6-tdk:build: [artifacts]         lineText: "import * as ocs_v2_apps_fileSharing_v1_shares from './ocs-v2-apps-file_sharing-v1-shares'",
@ownclouders/k6-tdk:build: [artifacts]         namespace: '',
@ownclouders/k6-tdk:build: [artifacts]         suggestion: ''
@ownclouders/k6-tdk:build: [artifacts]       },
@ownclouders/k6-tdk:build: [artifacts]       notes: [],
@ownclouders/k6-tdk:build: [artifacts]       pluginName: '',
@ownclouders/k6-tdk:build: [artifacts]       text: 'Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"'
@ownclouders/k6-tdk:build: [artifacts]     }
@ownclouders/k6-tdk:build: [artifacts]   ],
@ownclouders/k6-tdk:build: [artifacts]   warnings: []
@ownclouders/k6-tdk:build: [artifacts] }
@ownclouders/k6-tdk:build: [artifacts] 
@ownclouders/k6-tdk:build: [artifacts] Node.js v18.20.4
@ownclouders/k6-tdk:build: [artifacts]  ELIFECYCLE  Command failed with exit code 1.
@ownclouders/k6-tdk:build: [artifacts] pnpm run build:artifacts exited with code 1
@ownclouders/k6-tdk:build: [types] src/endpoints/index.ts(17,52): error TS2307: Cannot find module './ocs-v2-apps-file_sharing-v1-shares' or its corresponding type declarations.
@ownclouders/k6-tdk:build: [types]  ELIFECYCLE  Command failed with exit code 2.
@ownclouders/k6-tdk:build: [types] pnpm run build:types exited with code 2
@ownclouders/k6-tdk:build:  ELIFECYCLE  Command failed with exit code 1.
@ownclouders/k6-tdk:build: ERROR: command finished with error: command (/root/cdperf/packages/k6-tdk) pnpm run build exited (1)
command (/root/cdperf/packages/k6-tdk) pnpm run build exited (1)

 Tasks:    1 successful, 2 total
Cached:    1 cached, 2 total
  Time:    2.477s 
Failed:    @ownclouders/k6-tdk#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ScharfViktor** [comment]
> I cannot compile this:
> 
> ```
> # pnpm install
> Scope: all 6 workspace projects
>  WARN  1 deprecated subdependencies found: string-similarity@4.0.4
> Already up to date
> Progress: resolved 779, reused 731, downloaded 0, added 0, done
> Done in 2.4s
> # pnpm build
> 
> > @2.0.0-rc.5 build /root/cdperf
> > turbo run build --no-daemon
> 
> • Packages in scope: @ownclouders/eslint-config, @ownclouders/k6-tdk, @ownclouders/k6-tests, @ownclouders/tsconfig, @ownclouders/turbowatch
> • Running build in 5 packages
> • Remote caching disabled
> @ownclouders/turbowatch:build: cache hit, suppressing logs 44c192a886661f45
> @ownclouders/k6-tdk:build: cache miss, executing fd466463e1ce18a5
> @ownclouders/k6-tdk:build: 
> @ownclouders/k6-tdk:build: > @ownclouders/k6-tdk@0.0.1 build /root/cdperf/packages/k6-tdk
> @ownclouders/k6-tdk:build: > concurrently pnpm:build:*
> @ownclouders/k6-tdk:build: 
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [artifacts] > @ownclouders/k6-tdk@0.0.1 build:artifacts /root/cdperf/packages/k6-tdk
> @ownclouders/k6-tdk:build: [artifacts] > node build.mjs
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [types] 
> @ownclouders/k6-tdk:build: [types] > @ownclouders/k6-tdk@0.0.1 build:types /root/cdperf/packages/k6-tdk
> @ownclouders/k6-tdk:build: [types] > tsc --outDir dist/types
> @ownclouders/k6-tdk:build: [types] 
> @ownclouders/k6-tdk:build: [artifacts] CLI Building entry: src/index.ts, src/auth/index.ts, src/client/index.ts, src/endpoints/index.ts, src/values/index.ts, src/utils/index.ts
> @ownclouders/k6-tdk:build: [artifacts] CLI Using tsconfig: tsconfig.json
> @ownclouders/k6-tdk:build: [artifacts] CLI tsup v7.0.0
> @ownclouders/k6-tdk:build: [artifacts] CLI Building entry: src/index.ts, src/auth/index.ts, src/client/index.ts, src/endpoints/index.ts, src/values/index.ts, src/utils/index.ts
> @ownclouders/k6-tdk:build: [artifacts] CLI Using tsconfig: tsconfig.json
> @ownclouders/k6-tdk:build: [artifacts] CLI tsup v7.0.0
> @ownclouders/k6-tdk:build: [artifacts] CLI Target: esnext
> @ownclouders/k6-tdk:build: [artifacts] CJS Build start
> @ownclouders/k6-tdk:build: [artifacts] CJS You have emitDecoratorMetadata enabled but @swc/core was not installed, skipping swc plugin
> @ownclouders/k6-tdk:build: [artifacts] CLI Target: esnext
> @ownclouders/k6-tdk:build: [artifacts] ESM Build start
> @ownclouders/k6-tdk:build: [artifacts] ESM You have emitDecoratorMetadata enabled but @swc/core was not installed, skipping swc plugin
> @ownclouders/k6-tdk:build: [artifacts] ✘ [ERROR] Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [artifacts]     src/endpoints/index.ts:17:51:
> @ownclouders/k6-tdk:build: [artifacts]       17 │ ..._fileSharing_v1_shares from './ocs-v2-apps-file_sharing-v1-shares'
> @ownclouders/k6-tdk:build: [artifacts]          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [artifacts] ✘ [ERROR] Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [artifacts]     src/endpoints/index.ts:17:51:
> @ownclouders/k6-tdk:build: [artifacts]       17 │ ..._fileSharing_v1_shares from './ocs-v2-apps-file_sharing-v1-shares'
> @ownclouders/k6-tdk:build: [artifacts]          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [artifacts] CJS Build failed
> @ownclouders/k6-tdk:build: [artifacts] /root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1636
> @ownclouders/k6-tdk:build: [artifacts]   let error = new Error(`${text}${summary}`);
> @ownclouders/k6-tdk:build: [artifacts]               ^
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [artifacts] Error: Build failed with 1 error:
> @ownclouders/k6-tdk:build: [artifacts] src/endpoints/index.ts:17:51: ERROR: Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"
> @ownclouders/k6-tdk:build: [artifacts]     at failureErrorWithLog (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1636:15)
> @ownclouders/k6-tdk:build: [artifacts]     at /root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1048:25
> @ownclouders/k6-tdk:build: [artifacts]     at runOnEndCallbacks (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1471:45)
> @ownclouders/k6-tdk:build: [artifacts]     at buildResponseToResult (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1046:7)
> @ownclouders/k6-tdk:build: [artifacts]     at /root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:1075:16
> @ownclouders/k6-tdk:build: [artifacts]     at responseCallbacks.<computed> (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:697:9)
> @ownclouders/k6-tdk:build: [artifacts]     at handleIncomingPacket (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:752:9)
> @ownclouders/k6-tdk:build: [artifacts]     at Socket.readFromStdout (/root/cdperf/node_modules/.pnpm/esbuild@0.18.6/node_modules/esbuild/lib/main.js:673:7)
> @ownclouders/k6-tdk:build: [artifacts]     at Socket.emit (node:events:517:28)
> @ownclouders/k6-tdk:build: [artifacts]     at addChunk (node:internal/streams/readable:368:12) {
> @ownclouders/k6-tdk:build: [artifacts]   errors: [
> @ownclouders/k6-tdk:build: [artifacts]     {
> @ownclouders/k6-tdk:build: [artifacts]       detail: undefined,
> @ownclouders/k6-tdk:build: [artifacts]       id: '',
> @ownclouders/k6-tdk:build: [artifacts]       location: {
> @ownclouders/k6-tdk:build: [artifacts]         column: 51,
> @ownclouders/k6-tdk:build: [artifacts]         file: 'src/endpoints/index.ts',
> @ownclouders/k6-tdk:build: [artifacts]         length: 38,
> @ownclouders/k6-tdk:build: [artifacts]         line: 17,
> @ownclouders/k6-tdk:build: [artifacts]         lineText: "import * as ocs_v2_apps_fileSharing_v1_shares from './ocs-v2-apps-file_sharing-v1-shares'",
> @ownclouders/k6-tdk:build: [artifacts]         namespace: '',
> @ownclouders/k6-tdk:build: [artifacts]         suggestion: ''
> @ownclouders/k6-tdk:build: [artifacts]       },
> @ownclouders/k6-tdk:build: [artifacts]       notes: [],
> @ownclouders/k6-tdk:build: [artifacts]       pluginName: '',
> @ownclouders/k6-tdk:build: [artifacts]       text: 'Could not resolve "./ocs-v2-apps-file_sharing-v1-shares"'
> @ownclouders/k6-tdk:build: [artifacts]     }
> @ownclouders/k6-tdk:build: [artifacts]   ],
> @ownclouders/k6-tdk:build: [artifacts]   warnings: []
> @ownclouders/k6-tdk:build: [artifacts] }
> @ownclouders/k6-tdk:build: [artifacts] 
> @ownclouders/k6-tdk:build: [artifacts] Node.js v18.20.4
> @ownclouders/k6-tdk:build: [artifacts]  ELIFECYCLE  Command failed with exit code 1.
> @ownclouders/k6-tdk:build: [artifacts] pnpm run build:artifacts exited with code 1
> @ownclouders/k6-tdk:build: [types] src/endpoints/index.ts(17,52): error TS2307: Cannot find module './ocs-v2-apps-file_sharing-v1-shares' or its corresponding type declarations.
> @ownclouders/k6-tdk:build: [types]  ELIFECYCLE  Command failed with exit code 2.
> @ownclouders/k6-tdk:build: [types] pnpm run build:types exited with code 2
> @ownclouders/k6-tdk:build:  ELIFECYCLE  Command failed with exit code 1.
> @ownclouders/k6-tdk:build: ERROR: command finished with error: command (/root/cdperf/packages/k6-tdk) pnpm run build exited (1)
> command (/root/cdperf/packages/k6-tdk) pnpm run build exited (1)
> 
>  Tasks:    1 successful, 2 total
> Cached:    1 cached, 2 total
>   Time:    2.477s 
> Failed:    @ownclouders/k6-tdk#build
> 
>  ERROR  run failed: command  exited (1)
>  ELIFECYCLE  Command failed with exit code 1.
> ```

thanks 👍 . fixed it

**Pull request merged**
