### PR TITLE
add graph methods

### PR DESCRIPTION
**Pull request by ScharfViktor**
I switched creating and deleting user via graph for ocis

related: https://github.com/owncloud/ocis/issues/5638

### CODE REVIEW

**Comment by ScharfViktor** [comment]
I tested it and looks like it works: cc @butonic 

Screenshot 2023-03-01 at 11 14 04

and 
Screenshot 2023-03-01 at 11 25 03

**Comment by butonic** [comment]
@ScharfViktor hm ... I had to force the stresstest to use the graph api uses ... but I assume it should select the correct api based on the CLOUD_PROVIDER env var, right?

**Comment by ScharfViktor** [comment]
> @ScharfViktor hm ... I had to force the stresstest to use the graph api uses ... but I assume it should select the correct api based on the CLOUD_PROVIDER env var, right?

Yes, to work in oc10 too

**Comment by fschade** [comment]
@ScharfViktor can you please have a look to the next branch.

https://github.com/owncloud/cdperf/tree/next

this already uses the new graph api's....
we've decided to spent one day this sprint and make that banch the new master.

Please have a look if something is missing.

**Comment by ScharfViktor** [comment]
I see that PR #40  is underway development, because tests were failed for me.
But anyway you use graph api already and legacy api so I close my PR to favor your

**Comment by fschade** [comment]
@ScharfViktor thanks, sorry for stealing your time :(

**Comment by ScharfViktor** [comment]
> @ScharfViktor thanks, sorry for stealing your time :(

np, I got a little deeper into k6 testing and it is good. If you need some tests or anything else I would be happy to work with k6

**Pull request closed without merging**
